declare module "*hookform/resolvers/yup"
declare module "*react-hook-form"
declare module "*yup"
declare module "*@reduxjs/toolkit";
declare module "*@tanstack/react-query";
declare module "*react-redux";
declare module "*redux-persist";
declare module "*redux-persist/integration/react";
declare module "*redux-persist/lib/storage";
